[collections.rooms]
[[collections.rooms.indexes]]
fields = [['name']]

[collections.users]
[[collections.users.indexes]]
fields = [['name']]

[groups.authenticated.rules.read_users]
template = "collection('users').anyRead(userId())"

[groups.authenticated.rules.write_users]
template = "collection('users').anyWrite(userId())"

[groups.authenticated.rules.write_rooms]
template = "collection('rooms').anyWrite()"

[groups.default.rules.read_rooms]
template = "collection('rooms').anyRead()"
